version: '2.3'
services:
    tensorflow:
        container_name: nozomi_tensorflow
        image: nozomi0966/tensorflow:latest
        volumes:
                - $HOME/:/tf
                - /tmp/.X11-unix:/tmp/.X11-unix  
        devices:
                - "/dev/snd:/dev/snd"
        runtime: nvidia
        tty: true
        restart: always
        command: bash -c "xterm & /usr/local/bin/jupyter notebook --NotebookApp.token='nozomi' --ip=0.0.0.0 --allow-root"
        privileged: true
        environment: 
            - DISPLAY=$DISPLAY
        ports:
            - 8888:8888

